# Generated by Django 2.1.2 on 2018-10-03 00:15

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaSocial', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=50)),
                ('tipoPessoa', models.CharField(max_length=10)),
                ('cnpjCpf', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=18)),
                ('descricao', models.CharField(max_length=50)),
                ('numeroConta', models.CharField(max_length=20)),
                ('numeroAgencia', models.CharField(max_length=20)),
                ('saldoInicial', models.CharField(max_length=14)),
                ('tipo', multiselectfield.db.fields.MultiSelectField(choices=[('Caixa', 'Caixa'), ('Banco', 'Banco')], max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Contas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaSocial', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('tipoPessoa', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaSocial', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=50)),
                ('tipoPessoa', models.CharField(max_length=10)),
                ('cnpjCpf', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=14)),
                ('tipo', models.CharField(max_length=15)),
                ('caracteristica', multiselectfield.db.fields.MultiSelectField(choices=[('Caixa', 'Caixa'), ('Banco', 'Banco'), ('Cliente', 'Cliente'), ('Fornecedor', 'Fornecedor'), ('Entrade de Recursos', 'Entrade de Recursos'), ('Saída de Recursos', 'Saída de Recursos')], max_length=68)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ContasBancarias')),
            ],
            options={
                'verbose_name_plural': 'Plano de Contas',
            },
        ),
    ]
