# Generated by Django 2.1.2 on 2018-10-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20181006_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='razaSocial',
            new_name='razaoSocial',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='razaSocial',
            new_name='razaoSocial',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='razaSocial',
            new_name='razaoSocial',
        ),
    ]
