# Generated by Django 2.1.2 on 2018-10-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20181006_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baixaspagar',
            old_name='empresa',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='baixaspagar',
            old_name='caixaBanco',
            new_name='FormaPagamento',
        ),
        migrations.RenameField(
            model_name='baixaspagar',
            old_name='numeroDocumento',
            new_name='NumeroDocumento',
        ),
        migrations.RenameField(
            model_name='baixaspagar',
            old_name='valorRecebido',
            new_name='ValorRecebido',
        ),
        migrations.RenameField(
            model_name='baixaspagar',
            old_name='valorResidual',
            new_name='ValorResidual',
        ),
        migrations.RenameField(
            model_name='baixasreceber',
            old_name='caixaBanco',
            new_name='FormaPagamento',
        ),
        migrations.RenameField(
            model_name='lancamentospagar',
            old_name='Empresas',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='baixaspagar',
            name='dataBaixa',
        ),
        migrations.RemoveField(
            model_name='baixaspagar',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='baixaspagar',
            name='vencimentoPagamento',
        ),
        migrations.RemoveField(
            model_name='lancamentospagar',
            name='datEmissao',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='PlanoContas',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='datEmissao',
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='CaixaBanco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.PlanoContas'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='DataBaixa',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='Disponibilidade',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='VencimentoPagamento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='CaixaBanco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.PlanoContas'),
        ),
        migrations.AddField(
            model_name='lancamentospagar',
            name='dataEmissao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='Entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_entrada', to='financeiro.PlanoContas'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='Saida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_saida', to='financeiro.PlanoContas'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='dataEmissao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='baixasreceber',
            name='dataBaixa',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='baixasreceber',
            name='disponibilidade',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='baixasreceber',
            name='vencimentoPagamento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='dataSaldoInicial',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lancamentospagar',
            name='dataVencimento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lancamentospagar',
            name='numeroDocumento',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='lancamentosreceber',
            name='dataEmissao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lancamentosreceber',
            name='dataVencimento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tesouraria',
            name='dataDisponibilidade',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tesouraria',
            name='dataVencimento',
            field=models.DateField(auto_now=True),
        ),
    ]
