# Generated by Django 2.1.2 on 2018-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20181009_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixaspagar',
            name='DataBaixa',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='baixaspagar',
            name='Disponibilidade',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='baixaspagar',
            name='VencimentoPagamento',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
